services:
    zerobin:
      container_name: zerobin
      image: rnbj/zerobin:v1
      restart: always
      volumes:
          - './0binroot:/root'
      networks:
          - proxy

    nginxzerobin:
      container_name: nginxzerobin
      image: nginx:latest
      restart: unless-stopped
      ports:
          - "80:80"
          - "443:443"
      volumes:
          - ./nginx/htpasswd:/etc/nginx/conf.d/.htpasswd
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf
          - ./nginx/certs:/certs
          - ./nginx/cache:/var/nginx/cache
          - ./nginx/site:/usr/local/nginx/html
      networks:
          - proxy
          - host-network

networks:
    host-network:
        driver: bridge
    proxy:
        external:
            name: proxy
